// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emxeqpwtbyqwhqdhmvdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVteGVxcHd0Ynlxd2hxZGhtdmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzM5NzYsImV4cCI6MjA3MjY0OTk3Nn0.6t73Rof-yP9oNPYNE3UqZsMXuJxG6OWPTB2GRs_wqtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});